Add PromoteArtifactoryBuild
octopusden/octopus-artifactory-automation pull request #1
Opened 2024-10-22 15:59 UTC by aryabokon

2024-10-31 15:41 UTC, pgorbachev requested changes

2024-10-31 15:41 UTC, pgorbachev commented on metarunners/ArtifactoryPushDockerImageAndPublishBuild.xml
> +<meta-runner name="Docker Image Publisher to Artifactory Build">
Предлагаю вернуть поддержку podman
На старых версиях TC container.engine можно зафиксировать на уровне рут-проекта

2024-11-01 10:06 UTC, qu0d commented on README.md
> +- ARTIFACTORY_PASSWORD
Вроде говорил ему jfrog нужен, я бы отметил здесь

2024-11-01 10:37 UTC, qu0d commented on gradle.properties
> +version=2.0-SNAPSHOT
Сразу 2.0?

2024-11-01 10:42 UTC, aryabokon commented on gradle.properties
> +version=2.0-SNAPSHOT
у нас все компоненты на octopus начинаются сразу с 2.0

2024-11-01 10:45 UTC, qu0d commented on metarunners/ArtifactoryPromoteBuild.xml
ARTIFACTORY_TARGET_REPOSITORY один, разве билд не может положить артифакты в разные рпеозитории (RPM. DEB. DOCKER ...) ?

2024-11-01 10:52 UTC, aryabokon commented on metarunners/ArtifactoryPromoteBuild.xml
может, но это метараннер под один билд, похожий на метараннер из component-automation. Будет множественный промоут, но это вопрос вне скоупа этой задачи

2024-11-01 10:54 UTC, aryabokon commented on metarunners/ArtifactoryPushDockerImageAndPublishBuild.xml
> +<meta-runner name="Docker Image Publisher to Artifactory Build">
ок

2024-11-01 11:01 UTC, pgorbachev requested changes

2024-11-01 11:01 UTC, pgorbachev commented on metarunners/ArtifactoryPromoteDockerImage.xml
> +    <description>Promote Artifactory Build</description>
Description is incorrecct

2024-11-01 11:02 UTC, aryabokon commented on metarunners/ArtifactoryPromoteDockerImage.xml
> +    <description>Promote Artifactory Build</description>
согласен, внесу правки

2024-11-01 11:02 UTC, aryabokon commented on README.md
> +- ARTIFACTORY_PASSWORD
ок

2024-11-01 11:42 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/artifactory/Application.kt
> +const val SPLIT_SYMBOLS = "[,;]"
Не используется

2024-11-01 11:56 UTC, aryabokon commented on src/main/kotlin/org/octopusden/octopus/automation/artifactory/Application.kt
> +const val SPLIT_SYMBOLS = "[,;]"
Я знаю. Оставил специально как элемент для будущих метараннеров, использующих в качестве параметра перечисления. Сейчас я буду внедрять все это и в момент внедрения напишу множественные метараннеры - так что долго бесхозным лежать не будет

2024-11-01 12:24 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/artifactory/dto/BuildInfo.kt
DTO не data class специально?

2024-11-01 12:30 UTC, pgorbachev commented on metarunners/ArtifactoryPushDockerImageAndPublishBuild.xml
>              <param name="ARTIFACTORY_DOCKER_BUILD_NUMBER" value="%BUILD_VERSION%" />
DOCKER_IMAGE_NAME видится лучшим вариантом, но ок, up to you

2024-11-01 12:30 UTC, pgorbachev approved these changes, later dismissed

2024-11-01 12:31 UTC, aryabokon commented on src/main/kotlin/org/octopusden/octopus/automation/artifactory/dto/BuildInfo.kt
Вообще не должно быть DTO - все в клиенте. Это осталось от использования Artifactory Java Client

2024-11-01 12:33 UTC, aryabokon commented on metarunners/ArtifactoryPushDockerImageAndPublishBuild.xml
>              <param name="ARTIFACTORY_DOCKER_BUILD_NUMBER" value="%BUILD_VERSION%" />
ARTIFACTORY_DOCKER_IMAGE - нейминг внутри метараннера, могу у всех полей убрать ARTIFACTORY_, если не нравится. Суффикс _NAME не нужно вообще, т.к. в концепции докер это просто IMAGE

2024-11-01 12:34 UTC, qu0d submitted a review, later dismissed

2024-11-01 12:38 UTC, pgorbachev approved these changes

2024-11-01 12:39 UTC, qu0d approved these changes

2024-11-01 12:52 UTC, merged