Add a meta-runner for pushing and creating a build for multiple Docke…
octopusden/octopus-artifactory-automation pull request #9
Opened 2024-12-05 11:11 UTC by ozonophore

…r images.

2024-12-05 12:27 UTC, aryabokon commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +            <param name="ARTIFACTORY_DOCKER_IMAGES" value="%DISTRIBUTION_DOCKER_IMAGE_NAMES%" />
Эта переменная изменена в соседнем PR

2024-12-05 12:29 UTC, aryabokon requested changes, later dismissed
мы не можем поддерживать python

2024-12-06 09:22 UTC, ozonophore commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +            <param name="ARTIFACTORY_DOCKER_IMAGES" value="%DISTRIBUTION_DOCKER_IMAGE_NAMES%" />
исправил

2024-12-12 08:52 UTC, CamaradeRoman commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
Почему это условие нельзя применять на весь шаг, который запускает композитный метараннер?

2024-12-12 10:11 UTC, ozonophore commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
Можно и на весь. Одно другое не исключает

2024-12-12 11:12 UTC, CamaradeRoman commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
Я к тому что возможно это было бы более правильно, а композитный шаг должен либо выполняться целиком, либо не запускаться вообще (если опциональные шаги это не явная особенность логики исполнения)

2024-12-12 11:16 UTC, CamaradeRoman commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
В данном конкретном случае есть еще и важные особенности:

`<param name="ARTIFACTORY_DOCKER_IMAGES" value="%DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER%" />`

Этот параметр метараннера может быть спокойно переопределён на другое значение и параметр DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER будет брошен пустым. Это будет максимально неочевидно, почему пуш успешно прошёл, а публикация билда в артифактори вообще не запустилась.

2024-12-12 11:20 UTC, CamaradeRoman commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
Я считаю что данный condition требуется убрать из метараннера.

2024-12-12 11:21 UTC, CamaradeRoman requested changes

2024-12-12 11:21 UTC, CamaradeRoman commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
Я считаю что данный condition требуется убрать из метараннера.

2024-12-12 12:56 UTC, ozonophore commented on metarunners/ArtifactoryPushMultiDockerImagesAndPublishBuild.xml
> +                    <does-not-equal name="DISTRIBUTION_ARTIFACTS_COORDINATES_DOCKER" value="" />
убрал

2024-12-12 14:25 UTC, pgorbachev submitted a review, later dismissed

2024-12-16 09:00 UTC, fishinitself approved these changes

2024-12-16 16:20 UTC, CamaradeRoman approved these changes

2024-12-17 08:17 UTC, ozonophore commented
> мы не можем поддерживать python
Переделал на kotlin

2024-12-17 08:57 UTC, merged